version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            # - /C:/Users/caroline/Documents/Udacity/Capstone/Airflow/dags/:/usr/local/airflow/dags
            - ./dags:/usr/local/airflow/dags
            # - /C:/Users/caroline/Documents/Udacity/Udacity_Capstone/Data-Pipelines-with-Airflow/airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
            # - C:/Users/caroline/Documents/Udacity/Udacity_Capstone/Data-Pipelines-with-Airflow/airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3